version: '3.8'


services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
    - .env
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mad_db
      POSTGRES_USER: mad_user
      POSTGRES_PASSWORD: qwerty123
    ports:
      - 5432:5432
volumes:
  postgres_data: